name: ontrace_flutter_plugin_example
description: "Demonstrates how to use the ontrace_flutter_plugin plugin."
publish_to: 'none'
version: 1.0.0+1  # ✅ Format: MAJOR.MINOR.PATCH+BUILD_NUMBER

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.1"

dependencies:
  flutter:
    sdk: flutter
  ontrace_flutter_plugin:
    path: ../
  cupertino_icons: ^1.0.8

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
